/**
 * Workflow data model — shared contract between frontend and backend.
 * Backend Pydantic schemas mirror these types.
 *
 * `input` and `output` are NOT node types — the workflow's input comes
 * from `Workflow.run(input=...)` and the output is the last Step's
 * result. The canvas only carries the executable / tool-source nodes.
 *
 * row D : the per-node TypeScript config interfaces
 * used to live here as a hand mirror of
 * `backend/src/app/schemas/node_configs.py` (this file's lines
 * 99-330 prior to the codegen). Drift was easy. The mirror now lives
 * in `./node-configs.generated.ts`, regenerated by
 * `scripts/generate_node_configs_ts.py` and byte-pinned by
 * `scripts/check_node_configs_consistency.py`. We re-export the
 * generated types from here so existing imports
 * (`import type { AgentNodeConfig } from '../../types/workflow'`)
 * keep working unchanged.
 */

import type { GeneratedNodeType } from './workflow.generated'
import type {
  ConditionEvaluator,
  AskConfig,
  RouterSelector,
} from './node-configs.generated'

// ─────────────────────────────────────────────────────────────────
// Node types — manifest-derived (phase, )
// ─────────────────────────────────────────────────────────────────
// The literal union lives in `./workflow.generated.ts`, regenerated
// from `shared/nodes.manifest.json` by
// `scripts/generate_node_types.py`. The CI check
// `scripts/check_node_types_consistency.py` fails the build if the
// file drifts from the manifest. We re-export it as `NodeType` so
// existing imports (`import type { NodeType } from './workflow'`)
// keep working unchanged.
export type NodeType = GeneratedNodeType;

// ─────────────────────────────────────────────────────────────────
// MCP server (platform-wide, defined once and referenced by nodes)
// ─────────────────────────────────────────────────────────────────
export type McpTransport = 'stdio' | 'sse';

export interface McpServerConfig {
  id: string;
  name: string;
  transport: McpTransport;
  enabled: boolean;
  // stdio
  command?: string;
  args?: string[];
  env?: Record<string, string>;
  // sse / http
  url?: string;
  headers?: Record<string, string>;
  //  — per-user binding. NULL / undefined means a
  // system-shared row (visible to everyone, read-only via the API);
  // non-empty means the owning user's id. The Settings → MCP
  // editor uses this to disable the delete/edit affordances when
  // the row doesn't belong to the signed-in user.
  userId?: string | null;
}

// ─────────────────────────────────────────────────────────────────
// Per-node configs — codegen mirror of `node_configs.py` (D)
// ─────────────────────────────────────────────────────────────────
// `ModelConfig` and the 10 per-type config interfaces + the
// `NodeConfig` union are now codegen. See
// `./node-configs.generated.ts` for the source of truth.
export type {
  ModelConfig,
  AgentNodeConfig,
  // : `McpNodeConfig` + `HttpNodeConfig` +
  // `ToolsNodeConfig` collapsed to `ToolNodeConfig` (with `source`
  // discriminator).
  ToolNodeConfig,
  ParamSchema,
  ToolFunction,
  BranchTarget,
  BranchNodeConfig,
  RouterSelector,
  FlowNodeConfig,
  ConditionEvaluator,
  LoopNodeConfig,
  AskConfig,
  NodeConfig,
} from './node-configs.generated'

// Narrow aliases derived from the generated interfaces — kept here
// so the existing per-form mode arrays (`SELECTOR_MODES`,
// `EVALUATOR_MODES`) and per-field index accesses keep working
// without re-importing from `./node-configs.generated` directly.
export type RouterSelectorMode = RouterSelector['mode'];
export type ConditionEvaluatorMode = ConditionEvaluator['mode'];
// Top-level branch discriminator.
// `switch` = N-ary routing. `if-else` = binary condition.
export type BranchMode = 'switch' | 'if-else';
// Renamed from `HumanInputKind` — ask shares the
// same `inputType` Literal union (text | confirm | choice).
export type AskKind = AskConfig['inputType'];

// ─────────────────────────────────────────────────────────────────
// LLM presets (server-side, referenced by Agent nodes via ModelConfig.presetId)
// ─────────────────────────────────────────────────────────────────
// Not in `node_configs.py` — these are platform rows managed in
// Settings → LLM Models. Kept here as a hand-written TS mirror.
export interface LlmPreset {
  id: string;
  name: string;
  provider: 'openai' | 'anthropic' | 'ollama' | 'google' | string;
  modelId: string;
  hasApiKey: boolean;
  baseUrl?: string;
  isDefault: boolean;
  // P3 : per-preset "thinking mode" toggle. When true the
  // runtime adds the provider-specific reasoning kwargs
  // (Claude `thinking={"type":"enabled", ...}`,
  // OpenAI `reasoning_effort="medium"`, Gemini `thinking_budget=N`).
  // Surfaced by the Settings → LLM editor; absent for older presets.
  thinking?: boolean;
  //  — per-user binding. NULL / undefined means a
  // system-shared row (visible to everyone, read-only via the API);
  // non-empty means the owning user's id. The Settings → LLM editor
  // uses this to disable the delete/edit affordances when the row
  // doesn't belong to the signed-in user.
  userId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface LlmPresetCreate {
  name: string;
  provider: 'openai' | 'anthropic' | 'ollama' | 'google' | string;
  modelId: string;
  apiKey?: string;
  baseUrl?: string;
  isDefault?: boolean;
  // P3 : see `LlmPreset.thinking`. Optional on create —
  // the backend defaults to false when omitted.
  thinking?: boolean;
}

// ─────────────────────────────────────────────────────────────────
// Graph primitives
// ─────────────────────────────────────────────────────────────────
export interface WorkflowNode {
  id: string;
  type: NodeType;
  position: { x: number; y: number };
  data: {
    label: string;
    config: any;             // typed as NodeConfig by consumers
  };
}

export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
  sourceHandle?: string;     // router/parallel: branch id
  targetHandle?: string;
  /**
   * Edge kind () — drives which rule table the
   * frontend validator uses. Default `dataflow` is the existing
   * control-flow edge; `tool_attachment` is the new `tool-source →
   * agent` wiring that replaces cfg.toolsRef. Leave unset for legacy /
   * template edges so the validator falls back to `dataflow`.
   */
  kind?: 'dataflow' | 'tool_attachment';
}

export interface Workflow {
  id: string;
  name: string;
  description?: string;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
  mcpServers: McpServerConfig[];
  createdAt: string;
  updatedAt: string;
}

export interface WorkflowSummary {
  id: string;
  name: string;
  description?: string;
  isTemplate?: boolean;
  category?: string | null;
  /**
   * Locale tag (added ). Mirrors the JSON's `locale` field on
   * built-in templates (`en` vs `zh-CN`). Optional so legacy rows
   * without the column still project cleanly; treat absent as `"en"`.
   */
  locale?: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Lightweight projection of a built-in template for the gallery view.
 * Backend computes `nodeTypes` (deduplicated, in source order) so the
 * frontend can render colored chips without downloading the full
 * node/edge JSON.
 *
 * `locale` (added ) drives gallery filtering — the gallery
 * auto-follows the UI's current i18n locale and shows only templates
 * with the matching `locale`. Defaults to `"en"` when the field is
 * absent (legacy rows that pre-date the column).
 */
export interface TemplateSummary {
  id: string;
  name: string;
  description?: string;
  category?: string | null;
  isTemplate: boolean;
  locale?: string;
  nodeTypes: NodeType[];
  nodeCount: number;
  edgeCount: number;
}

// ─────────────────────────────────────────────────────────────────
// Runtime SSE event types (backend -> frontend during execution)
// ─────────────────────────────────────────────────────────────────
export type RuntimeEvent =
  | { type: 'text'; content: string }
  | { type: 'tool_call'; tool: string; args: Record<string, unknown> }
  | { type: 'tool_result'; tool: string; result: unknown; ok?: boolean }
  | {
      type: 'confirmation';
      // : ConfirmationEvent.kind renamed from
      // "human_input" to "ask" for SSE symmetry with the backend.
      kind: 'tool_confirm' | 'ask';
      prompt: string;
      choices?: string[];
      toolCallId?: string;
    }
  | { type: 'completed'; output: string }
  | { type: 'error'; message: string }
  | { type: 'node_start'; nodeId: string; nodeType: NodeType; label: string; t: number }
  | {
      type: 'node_end';
      nodeId: string;
      status: 'ok' | 'error';
      durationMs: number;
      error?: string;
      tokens?: { input: number; output: number; total: number };
      t: number;
    };